# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - perseverancehealthcare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f142ce818ea142f4bbd6dccce245fe7b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9f81e6f6a62d4db9b0a321a819a2dcf9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f142ce818ea142f4bbd6dccce245fe7b }}/ui-v2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'perseverancehealthcare'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0532684c906544f4ac063390a60c9bcf }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f142ce818ea142f4bbd6dccce245fe7b }}/ui-v2:${{ github.sha }}'